name: Fetch Featured Issues

on:
  issues:
    types: [opened, labeled]

jobs:
  fetch-issues:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Fetch Featured Issues
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Fetch all open issues labeled as "featured"
        issues=$(gh issue list --limit 1000 --state open --label "featured" --json number,title,url)
        
        # Save the issues to a featured-issues.md file
        echo "$issues" | jq > packages/frontendmu-data/data/featured-issues.json
        
        # Commit the changes
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "GitHub Action[bot]"
        git add packages/frontendmu-data/data/featured-issues.json
        git commit -m "Update featured issues"
        git push
