name: Playwright CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20  # Replace with the latest Node.js version

    - name: Install dependencies
      run: |
        npm install -g pnpm
        pnpm install --no-frozen-lockfile

    - name: Install Browsers
      run: pnpm exec playwright install

    - name: Run Playwright tests
      run: |
        pnpm run test
