name: Update Contributors

on:
  push:
    branches:
      - main # Change 'main' to your default branch name if it's different

jobs:
  update-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

      - name: Install dependencies
        # Exclude the Nuxt package when running pnpm install
        run: pnpm install --filter astro --filter data

      - name: Update Contributors Astro
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run astro update-contributors

      - name: Update Contributors Nuxt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run data update-contributors
