name: Update Contributors

on:
  push:
    branches:
      - main # Change 'main' to your default branch name if it's different

  pull_request:
    types:
      - closed

jobs:
  update-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

      # - name: Install Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: "18"

      - name: Install dependencies
        run: pnpm install

      - name: Update Contributors
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run astro update-contributors
