name: Update Contributors

on:
  push:
    branches:
      - main # Change 'main' to your default branch name if it's different
      - feature/automatic-contributors

  pull_request:
    types:
      - closed

jobs:
  update-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install

      - name: Update Contributors
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run update-contributors
