name: Update Contributors

on:
  pull_request_target:
    types:
      - closed
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  update-contributors:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

      - name: Install dependencies
        # Exclude the Nuxt package when running pnpm install
        run: pnpm install --filter astro --filter data

      - name: Update Contributors Astro
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run astro update-contributors

      - name: Update Contributors Nuxt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run data update-contributors
